##微信用户表
#DROP TABLE IF EXISTS Tbl_WeixinAuthUser
CREATE TABLE `Tbl_WeixinAuthUser` (
    `FUserId` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    `FOpenId` VARCHAR(255) NOT NULL COMMENT 'weixin openid',
    `FNick` VARCHAR(255) NOT NULL COMMENT 'base64_encode后的用户昵称',
    `FNickname` VARCHAR(255) NOT NULL COMMENT '用户昵称',
    `FSex` TINYINT UNSIGNED DEFAULT 0 NOT NULL COMMENT '用户的性别，值为1时是男性，值为2时是女性，值为0时是未知',
    `FProvince` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户个人资料填写的省份',
    `FCity` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '普通用户个人资料填写的城市',
    `FCountry` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '国家，如中国为CN',
    `FHead` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户头像',
    `FTime` DATETIME NOT NULL DEFAULT '00-00-00 00:00:00' COMMENT '授权时间',
    `FDate` DATE NOT NULL DEFAULT '00-00-00' COMMENT '授权日期',
    `FIp` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '加入IP',
    `FValue1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备用字段1',
    `FValue2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备用字段2',
    PRIMARY KEY (`FUserId`),
    UNIQUE INDEX `INDEX_FOpenId` (`FOpenId`),
    INDEX `INDEX_FDATE` (`FDate`) #用于按日期查询用户列表
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


##发送红包的记录表
#DROP TABLE IF EXISTS Tbl_FSendRedpack
CREATE TABLE Tbl_FSendRedpack(
 `FId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 `FOpenId` VARCHAR(255) NOT NULL COMMENT '接收红包者openid',
 `FMchBillNo` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '商户订单编号，唯一',
 `FReturnCode` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '通信标识',
 `FReturnMsg` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '返回信息',
 `FResultCode` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '交易结果',
 `FErrCodeDes` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '结果信息描述',
 `FSendTime` DATETIME NOT NULL DEFAULT '00-00-00 00:00:00' COMMENT '发红包时间',
 `FSendDate` DATE NOT NULL DEFAULT '00-00-00' COMMENT '发红包日期',
 `FTotalAmount` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '付款金额/分',
 `FStatus` TINYINT NOT NULL DEFAULT '1' COMMENT '红包状态，1为未发，2为已发，3为失败',
 `FIp` VARCHAR(16) NOT NULL DEFAULT '' COMMENT 'IP',
 `FCreateTime` DATETIME NOT NULL DEFAULT '00-00-00 00:00:00' COMMENT '创建时间',
 `FCreateDate` DATE NOT NULL DEFAULT '00-00-00' COMMENT '创建日期',
  PRIMARY KEY (`FId`),
  INDEX `INDEX_FOpenId` (`FOpenId`),
  INDEX `INDEX_FSTATUS` (`FStatus`),
  INDEX `INDEX_FMchBillNo`(`FMchBillNo`)
)ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

##红包发送成功的流水记录
#DROP TABLE if exists Tbl_FSendRedhistory
CREATE TABLE `Tbl_FSendRedhistory` (
    `FId` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '流水ID',
    `FMchBillNo` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '商户订单编号，唯一',
    `FReturnCode` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '通信标识',
    `FReturnMsg` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '返回信息',
    `FResultCode` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '交易结果',
    `FReOpenId` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口返回的openid',
    `FTotalAmount` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '红包金额',
    `FSendTime` DATETIME NOT NULL DEFAULT '00-00-00 00:00:00' COMMENT '发红包时间',
    `FSendDate` DATE NOT NULL DEFAULT '00-00-00' COMMENT '发红包日期',
    `FValue1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备用字段1',
    `FValue2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备用字段2',
    PRIMARY KEY (`FId`),
    INDEX `INDEX_FBILLNO` (`FMchBillNo`),
    INDEX `INDEX_FRESULT_CODE` (`FResultCode`),
    INDEX `INDEX_FSENDDATE` (`FSendDate`) #用于按日期查询用户列表
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
